### ISSUE TITLE
configure a permanent redirect (301) from one host to another via a route

### ISSUE THREAD

**Issue by callum-stakater** [openshift/router#425]
Hunting for ways to configure a route (ocp 4.10 haproxy) to simply 301 redirect to a new hostname

HAProxy seems to support this with something like:

`http-request redirect prefix http://api.domain.com code 301 if { hdr(host) -i 123.domain.com }`

We do this with ingress-nginx via an annotation like:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-redirect
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: https://new-domain.dev/foo/bar
spec:
  ingressClassName: external
  rules:
    - host: dev.domain.dev
      http:
        paths:
          - backend:
              service:
                name: dev
                port:
                  number: 80
            pathType: ImplementationSpecific
```

is there really no way to achieve the same thing with openshift route?

As far as I can tell there also isnt a way to pass a server-snippet similar to what nginx ingress allows?
