### ISSUE TITLE
HAProxy should be configured to compare Host header with SNI and return 421 on mismatch

### ISSUE THREAD

**Issue by therealak12** [openshift/router#535]
Hi.

We've encountered an issue with the way HAProxy handles requests when the `SNI` and the `Host` header differ. Currently, HAProxy seems to route requests based solely on the Host header without comparing it to the SNI presented during the TLS handshake. 

This can lead to requests being improperly routed when a client inadvertently (e.g. when reusing a connection for a.example.com for b.example.com assuming both use a certificate signed for *.example.com) or maliciously sends an incorrect Host header that does not match the SNI. According to RFC 7540 Section 9.1.2, when a server encounters a mismatch, it should respond with a 421 Misdirected Request error.

We propose a change like the following line to fix the issue:
```
http-request deny deny_status 421 if { ssl_fc_has_sni } { ssl_c_used } !ssl_sni_http_host_match
```

This change would enhance security and reliability by ensuring that requests are correctly routed to the intended service.

**Comment by candita** [comment]
@therealak12 can you provide the version of OpenShift and the route configuration for a route that has this issue?

**Comment by therealak12** [comment]
OKD version:
4.10.0-0.okd-2022-03-07-131213

Router version:
4.10.0-0.okd-2022-03-07-131213

**Comment by therealak12** [comment]
Here's a route that has the issue:

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    router: shard-1
  name: sample-service
  namespace: sample
spec:
  host: sample-service.our-domain.com
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: sample-service
    weight: 100
  wildcardPolicy: None
  ```

The configured HAProxy will route the following request to the pods behind `sample-service`. (The routers use a common certificate signed for `*.our-domain.com`).
  
  ```
  curl "https://fake-host.our-domain.com" -H 'Host: sample-service.our-domain.com' -vvvv
  ```
